export const AchievementNames = Object.freeze([
    "",
    "Magdalene",
    "Cain",
    "Judas",
    "The Womb",
    "The Harbingers",
    "A Cube of Meat",
    "The Book of Revelations",
    "A Noose",
    "The Nail",
    "A Quarter",
    "A Fetus in a Jar",
    "A Small Rock",
    "Monstro's Tooth",
    "Lil' Chubby",
    "Loki's Horns",
    "Something From The Future",
    "Something Cute",
    "Something Sticky",
    "A Bandage",
    "A Cross",
    "A Bag of Pennies",
    "The Book of Sin",
    "Little Gish",
    "Little Steven",
    "Little C.H.A.D.",
    "A Gamekid",
    "A Halo",
    "Mr. Mega",
    "The D6",
    "The Scissors",
    "The Parasite",
    "???",
    "Everything Is Terrible!!!",
    "It Lives!",
    "Mom's Contact",
    "The Necronomicon",
    "Basement Boy",
    "Spelunker Boy",
    "Dark Boy",
    "Mama's Boy",
    "Golden God!",
    "Eve",
    "Mom's Knife",
    "The Razor",
    "Guardian Angel",
    "A Bag of Bombs",
    "Demon Baby",
    "Forget Me Now",
    "The D20",
    "Celtic Cross",
    "Abel",
    "Curved Horn",
    "Sacrificial Dagger",
    "Bloody Lust",
    "Blood Penny",
    "Blood Rights",
    "The Polaroid",
    "Dad's Key",
    "Blue Candle",
    "Burnt Penny",
    "Lucky Toe",
    "Epic Fetus",
    "SMB Super Fan",
    "Counterfeit Coin",
    "Guppy's Hairball",
    "A Forgotten Horseman",
    "Samson",
    "Something Icky",
    "!Platinum God!",
    "Isaac's Head",
    "Maggy's Faith",
    "Judas' Tongue",
    "???'s Soul",
    "Samson's Lock",
    "Cain's Eye",
    "Eve's Bird Foot",
    "The Left Hand",
    "The Negative",
    "Azazel",
    "Lazarus",
    "Eden",
    "The Lost",
    "Dead Boy",
    "The Real Platinum God",
    "Lucky Rock",
    "The Cellar",
    "The Catacombs",
    "The Necropolis",
    "Rune of Hagalaz",
    "Rune of Jera",
    "Rune of Ehwaz",
    "Rune of Dagaz",
    "Rune of Ansuz",
    "Rune of Perthro",
    "Rune of Berkano",
    "Rune of Algiz",
    "Chaos Card",
    "Credit Card",
    "Rules Card",
    "Card Against Humanity",
    "Swallowed Penny",
    "Robo-Baby 2.0",
    "Death's Touch",
    "Technology .5",
    "Missing No.",
    "Isaac's Tears",
    "Guillotine",
    "Judas' Shadow",
    "Maggy's Bow",
    "Cain's Other Eye",
    "Black Lipstick",
    "Eve's Mascara",
    "Fate",
    "???'s Only Friend",
    "Samson's Chains",
    "Lazarus' Rags",
    "Broken Ankh",
    "Store Credit",
    "Pandora's Box",
    "Suicide King",
    "Blank Card",
    "Book of Secrets",
    "Mysterious Paper",
    "Mystery Sack",
    "Undefined",
    "Satanic Bible",
    "Daemon's Tail",
    "Abaddon",
    "Isaac's Heart",
    "The Mind",
    "The Body",
    "The Soul",
    "The D100",
    "Blue Map",
    "There's Options",
    "Black Candle",
    "Red Candle",
    "Stop Watch",
    "Wire Coat Hanger",
    "Ipecac",
    "Experimental Treatment",
    "Krampus",
    "Head of Krampus",
    "Super Meat Boy",
    "Butter Bean",
    "Little Baggy",
    "Blood Bag",
    "The D4",
    "Missing Poster",
    "Rubber Cement",
    "Store Upgrade lv.1",
    "Store Upgrade lv.2",
    "Store Upgrade lv.3",
    "Store Upgrade lv.4",
    "Angels",
    "Godhead",
    "Darkness Falls",
    "The Tank",
    "Solar System",
    "Suicide King",
    "Cat Got Your Tongue",
    "Demo Man",
    "Cursed!",
    "Glass Cannon",
    "The Family Man",
    "Purist",
    "Lost Baby",
    "Cute Baby",
    "Crow Baby",
    "Shadow Baby",
    "Glass Baby",
    "Wrapped Baby",
    "Begotten Baby",
    "Dead Baby",
    "-0- Baby",
    "Glitch Baby",
    "Fighting Baby",
    "Lord of the Flies",
    "Fart Baby",
    "Purity",
    "D12",
    "Betrayal",
    "Fate's Reward",
    "Athame",
    "Blind Rage",
    "Maw of the Void",
    "Empty Vessel",
    "Eden's Blessing",
    "Sworn Protector",
    "Incubus",
    "Keeper now holds... A Penny!",
    "Lil' Chest",
    "Censer",
    "Evil Eye",
    "My Shadow",
    "Cracked Dice",
    "Black Feather",
    "Lusty Blood",
    "Lilith",
    "Key Bum",
    "GB Bug",
    "Zodiac",
    "Box of Friends",
    "Rib of Greed",
    "Cry Baby",
    "Red Baby",
    "Green Baby",
    "Brown Baby",
    "Blue Baby",
    "Lil' Baby",
    "Rage Baby",
    "Black Baby",
    "Long Baby",
    "Yellow Baby",
    "White Baby",
    "Big Baby",
    "Noose Baby",
    "Rune Bag",
    "Cambion Conception",
    "Serpent's Kiss",
    "Succubus",
    "Immaculate Conception",
    "Goat Head Baby",
    "Gold Heart",
    "Get out of Jail Free Card",
    "Gold Bomb",
    "2 new pills",
    "2 new pills",
    "Poker Chip",
    "Stud Finder",
    "D8",
    "Kidney Stone",
    "Blank Rune",
    "Blue Womb",
    "1001%",
    "Keeper holds Wooden Nickel",
    "Keeper holds Store Key",
    "Deep Pockets",
    "Karma",
    "Sticky Nickels",
    "Super Greed Baby",
    "Lucky Pennies",
    "Special Hanging Shopkeepers",
    "Wooden Nickel",
    "Cain holds Paperclip",
    "Everything is Terrible 2!!!",
    "Special Shopkeepers",
    "Eve now holds Razor Blade",
    "Store Key",
    "Lost holds Holy Mantle",
    "Keeper",
    "Hive Baby",
    "Buddy Baby",
    "Colorful Baby",
    "Whore Baby",
    "Cracked Baby",
    "Dripping Baby",
    "Blinding Baby",
    "Sucky Baby",
    "Dark Baby",
    "Picky Baby",
    "Revenge Baby",
    "Belial Baby",
    "Sale Baby",
    "XXXXXXXXL",
    "SPEED!",
    "Blue Bomber",
    "PAY TO PLAY",
    "Have a Heart",
    "I RULE!",
    "BRAINS!",
    "PRIDE DAY!",
    "Onan's Streak",
    "The Guardian",
    "Generosity",
    "Mega",
    "Backasswards",
    "Aprils fool",
    "Pokey Mans",
    "Ultra Hard",
    "PONG",
    "D infinity",
    "Eucharist",
    "Silver Dollar",
    "Shade",
    "King Baby",
    "Bloody Crown",
    "Dull Razor",
    "Eden's Soul",
    "Dark Prince's Crown",
    "Compound Fracture",
    "Euthanasia",
    "Holy Card",
    "Crooked Penny",
    "Void",
    "D1",
    "Glyph of Balance",
    "Sack of Sacks",
    "Eye of Belial",
    "Meconium",
    "Stem Cell",
    "Crow Heart",
    "Metronome",
    "Bat Wing",
    "Plan C",
    "Duality",
    "Dad's Lost Coin",
    "Eye of Greed",
    "Black Rune",
    "Locust of Wrath",
    "Locust of Pestilence",
    "Locust of Famine",
    "Locust of Death",
    "Locust of Conquest",
    "Hushy",
    "Brown Nugget",
    "Mort Baby",
    "Smelter",
    "Apollyon Baby",
    "New Area",
    "Once More with Feeling!",
    "Hat trick!",
    "5 Nights at Mom's",
    "Sin collector",
    "Dedication",
    "ZIP!",
    "It's the Key",
    "Mr. Resetter!",
    "Living on the edge",
    "U Broke It!",
    "Laz Bleeds More!",
    "Maggy Now Holds a Pill!",
    "Charged Key",
    "Samson Feels Healthy!",
    "Greed's Gullet",
    "The Marathon",
    "RERUN",
    "Delirious",
    "1000000%",
    "Apollyon",
    "Greedier!",
    "Burning Basement",
    "Flooded Caves",
    "Dank Depths",
    "Scarred Womb",
    "Something wicked this way comes!",
    "Something wicked this way comes+!",
    "The gate is open!",
    "Black Hole",
    "Mystery Gift",
    "Sprinkler",
    "Angry Fly",
    "Bozo",
    "Broken Modem",
    "Buddy in a Box",
    "Fast Bombs",
    "Lil Delirium",
    "Hairpin",
    "Wooden Cross",
    "Butter!",
    "Huge Growth",
    "Ancient Recall",
    "Era Walk",
    "Coupon",
    "Telekinesis",
    "Moving Box",
    "Jumper Cables",
    "Leprosy",
    "Technology Zero",
    "Filigree Feather",
    "Mr. ME!",
    "7 Seals",
    "Angelic Prism",
    "Pop!",
    "Door Stop",
    "Death's List",
    "Haemolacria",
    "Lachryphagy",
    "Schoolbag",
    "Trisagion",
    "Extension Cord",
    "Flat Stone",
    "Sacrificial Altar",
    "Lil Spewer",
    "Blanket",
    "Marbles",
    "Mystery Egg",
    "Rotten Penny",
    "Baby-Bender",
    "The Forgotten",
    "Bone Heart",
    "Marrow",
    "Slipped Rib",
    "Pointy Rib",
    "Jaw Bone",
    "Brittle Bones",
    "Divorce Papers",
    "Hallowed Ground",
    "Finger Bone",
    "Dad's Ring",
    "Book of the Dead",
    "Bone Baby",
    "Bound Baby",
    "Bethany",
    "Jacob and Esau",
    "The Planetarium",
    "A Secret Exit",
    "Forgotten Lullaby",
    "Fruity Plum",
    "Plum Flute",
    "Rotten Heart",
    "Dross",
    "Ashpit",
    "Gehenna",
    "Red Key",
    "Wisp Baby",
    "Book of Virtues",
    "Urn of Souls",
    "Blessed Penny",
    "Alabaster Box",
    "Beth's Faith",
    "Soul Locket",
    "Divine Intervention",
    "Vade Retro",
    "Star of Bethlehem",
    "Hope Baby",
    "Glowing Baby",
    "Double Baby",
    "The Stairway",
    "Red Stew",
    "Birthright",
    "Damocles",
    "Rock Bottom",
    "Inner Child",
    "Vanishing Twin",
    "Genesis",
    "Suplex!",
    "Solomon's Baby",
    "Illusion Baby",
    "Meat Cleaver",
    "Options?",
    "Yuck Heart",
    "Candy Heart",
    "Guppy's Eye",
    "A Pound of Flesh",
    "Akeldama",
    "Redemption",
    "Eternal D6",
    "Montezuma's Revenge",
    "Bird Cage",
    "Cracked Orb",
    "Bloody Gust",
    "Empty Heart",
    "Devil's Crown",
    "Lil Abaddon",
    "Tinytoma",
    "Astral Projection",
    "'M",
    "Everything Jar",
    "Lost Soul",
    "Hungry Soul",
    "Blood Puppy",
    "C Section",
    "Keeper's Sack",
    "Keeper's Box",
    "Lil Portal",
    "Worm Friend",
    "Bone Spurs",
    "Spirit Shackles",
    "Revelation",
    "Jar of Wisps",
    "Magic Skin",
    "Friend Finder",
    "The Broken",
    "The Dauntless",
    "The Hoarder",
    "The Deceiver",
    "The Soiled",
    "The Curdled",
    "The Savage",
    "The Benighted",
    "The Enigma",
    "The Capricious",
    "The Baleful",
    "The Harlot",
    "The Miser",
    "The Empty",
    "The Fettered",
    "The Zealot",
    "The Deserter",
    "Glitched Crown",
    "Belly Jelly",
    "Blue Key",
    "Sanguine Bond",
    "The Swarm",
    "Heartbreak",
    "Larynx",
    "Azazel's Rage",
    "Salvation",
    "TMTRAINER",
    "Sacred Orb",
    "Twisted Pair",
    "Strawman",
    "Echo Chamber",
    "Isaac's Tomb",
    "Vengeful Spirit",
    "Esau Jr.",
    "Bloody Mary",
    "Baptism by Fire",
    "Isaac's Awakening",
    "Seeing Double",
    "Pica Run",
    "Hot Potato",
    "Cantripped!",
    "Red Redemption",
    "DELETE THIS",
    "Dirty Mind",
    "Sigil of Baphomet",
    "Purgatory",
    "Spirit Sword",
    "Broken Glasses",
    "Ice Cube",
    "Charged Penny",
    "The Fool",
    "The Magician",
    "The High Priestess",
    "The Empress",
    "The Emperor",
    "The Hierophant",
    "The Lovers",
    "The Chariot",
    "Justice",
    "The Hermit",
    "Wheel of Fortune",
    "Strength",
    "The Hanged Man",
    "Death",
    "Temperance",
    "The Devil",
    "The Tower",
    "The Stars",
    "The Sun and the Moon",
    "Judgement",
    "The World",
    "Old Capacitor",
    "Brimstone Bombs",
    "Mega Mush",
    "Mom's Lock",
    "Dice Bag",
    "Holy Crown",
    "Mother's Kiss",
    "Gilded Key",
    "Lucky Sack",
    "Your Soul",
    "Number Magnet",
    "Dingle Berry",
    "Ring Cap",
    "Strange Key",
    "Lil Clot",
    "Temporary Tattoo",
    "Swallowed M80",
    "Wicked Crown",
    "Azazel's Stump",
    "Torn Pocket",
    "Torn Card",
    "Nuh Uh!",
    "Modeling Clay",
    "Kid's Drawing",
    "Crystal Key",
    "The Twins",
    "Adoption Papers",
    "Keeper's Bargain",
    "Cursed Penny",
    "Cricket Leg",
    "Apollyon's Best Friend",
    "Polished Bone",
    "Hollow Heart",
    "Expansion Pack",
    "Beth's Essence",
    "RC Remote",
    "Found Soul",
    "Member Card",
    "Golden Razor",
    "Spindown Dice",
    "Hypercoagulation",
    "Bag of Crafting",
    "Dark Arts",
    "IBS",
    "Sumptorium",
    "Berserk!",
    "Hemoptysis",
    "Flip",
    "Corrupted Data",
    "Ghost Bombs",
    "Gello",
    "Keeper's Kin",
    "Abyss",
    "Decap Attack",
    "Lemegeton",
    "Anima Sola",
    "Mega Chest",
    "Queen of Hearts",
    "Gold Pill",
    "Black Sack",
    "Charming Poop",
    "Horse Pill",
    "Crane Game",
    "Hell Game",
    "Wooden Chest",
    "Wild Card",
    "Haunted Chest",
    "Fool's Gold",
    "Golden Penny",
    "Rotten Beggar",
    "Golden Battery",
    "Confessional",
    "Golden Trinket",
    "Soul of Isaac",
    "Soul of Magdalene",
    "Soul of Cain",
    "Soul of Judas",
    "Soul of ???",
    "Soul of Eve",
    "Soul of Samson",
    "Soul of Azazel",
    "Soul of Lazarus",
    "Soul of Eden",
    "Soul of the Lost",
    "Soul of Lilith",
    "Soul of the Keeper",
    "Soul of Apollyon",
    "Soul of the Forgotten",
    "Soul of Bethany",
    "Soul of Jacob and Esau",
    "A Strange Door",
    "Death Certificate",
    "Dead God",
    "Play Online",
    "Win Online",
    "Win Online Daily",
    "Item Descriptions",
]);

export const AchievementUnlocks = Object.freeze([
    "",
    "Have 7 or more Red Heart Containers at one time",
    "Hold 55 Coins at one time",
    "Defeat Satan",
    "Defeat Mom",
    "Defeat Mom",
    "Defeat Mom",
    "Defeat a Harbinger",
    "Defeat Mom's Heart 3 times",
    "Complete the Boss Rush as Azazel",
    "Defeat Mom's Heart 8 times",
    "Defeat Mom's Heart 9 times",
    "Destroy 100 Tinted Rocks",
    "Beat Chapter 1",
    "Beat Chapter 2",
    "Defeat Lokii",
    "Beat Basement 40 times",
    "Beat Chapter 2 30 times",
    "Beat Chapter 3 20 times",
    "Make a Super Bandage Girl by picking up 4 copies of Ball of Bandages in one run",
    "Defeat Isaac as Magdalene",
    "Defeat Isaac as Cain",
    "Defeat all 7 Deadly Sins",
    "Defeat Gish",
    "Defeat Steven",
    "Defeat C.H.A.D.",
    "Visit 10 Arcades",
    "Defeat Mom, Mom's Heart, or It Lives! using The Bible",
    "Destroy 10 Tinted Rocks",
    "Defeat Isaac as ???",
    "Die 100 times",
    "Pick up any 2 of the following items in a single run: Bob's Rotten Head, Dead Cat, Cricket's Head, and Tammy's Head (Any 2 items that have the 'dead' item tag)",
    "Defeat Mom's Heart 10 times",
    "Defeat Mom's Heart 5 times",
    "Defeat Mom's Heart 11 times",
    "Obtain three Yes Mother? items in one run",
    "Use XIII - Death 4 times",
    "Beat Chapter 1 without taking damage",
    "Beat Chapter 2 without taking damage",
    "Beat Chapter 3 without taking damage",
    "Beat Chapter 4 without taking damage",
    "Defeat ??? and The Lamb",
    "Don't pick up any Hearts for 2 floors in a row",
    "Defeat Satan as Isaac",
    "Defeat Satan as Eve",
    "Defeat Satan as Magdalene",
    "Defeat Satan as Cain",
    "Defeat The Lamb as Azazel",
    "Defeat Satan as ???",
    "Defeat ??? as Isaac",
    "Defeat ??? as Magdalene",
    "Defeat The Lamb as Cain",
    "Defeat The Lamb as Judas",
    "Defeat ??? as Eve",
    "Defeat Isaac as Samson",
    "Defeat ??? as Samson",
    "Defeat Satan as Samson",
    "Defeat Isaac 5 times",
    "Pick up both Key Pieces from the Angels in one run",
    "Donate 900 coins to the Donation Machine",
    "Complete Beans! (challenge #13)",
    "Blow up 20 Shopkeepers",
    "Complete The Family Man (challenge #19)",
    "Complete It's in the Cards (challenge #14)",
    "Play either Shell Game or Hell Game 100 times",
    "Become Guppy",
    "Take 10 Angel Room items",
    "Complete 2 floors in a row without taking damage",
    "Defeat Isaac 10 times",
    "Collect all non-DLC items in the game, and unlock all of the secrets and endings (minus The Lost)",
    "Complete the Boss Rush as Isaac",
    "Defeat The Lamb as Magdalene",
    "Defeat Satan as Judas",
    "Defeat The Lamb as ???",
    "Defeat The Lamb as Samson",
    "Defeat ??? as Cain",
    "Defeat Isaac as Eve",
    "Defeat Ultra Pride as any character, or ??? as Judas",
    "Defeat Satan 5 times",
    "Make 3 Deals with the Devil in one run",
    "Have 4 or more Soul Hearts at one time",
    "Complete Chapter 4",
    "Die in a Sacrifice Room while holding the Missing Poster trinket",
    "Complete Chapter 6 without taking damage",
    "Collect every non-DLC item, and unlock every secret and ending.",
    "Destroy 100 rocks",
    "Beat all Basement bosses (except Baby Plum) (not restricted to beating bosses in The Basement)",
    "Beat all Caves bosses (except Bumbino) (not restricted to beating bosses in The Caves)",
    "Beat all Depths bosses (except Reap Creep) (not restricted to beating bosses in The Depths)",
    "Complete Pitch Black (challenge #1)",
    "Complete High Brow (challenge #2)",
    "Complete Head Trauma (challenge #3)",
    "Complete Darkness Falls (challenge #4)",
    "Complete The Tank (challenge #5)",
    "Complete Solar System (challenge #6)",
    "Complete Purist (challenge #20)",
    "Complete Cat Got Your Tongue (challenge #8)",
    "Complete Demo Man (challenge #9)",
    "Complete Cursed! (challenge #10)",
    "Complete Glass Cannon (challenge #11)",
    "Complete When Life Gives You Lemons (challenge #12)",
    "Complete Slow Roll (challenge #15)",
    "Complete Computer Savvy (challenge #16)",
    "Complete Waka Waka (challenge #17)",
    "Complete The Host (challenge #18)",
    "Complete the Boss Rush as Lazarus",
    "Defeat Isaac as Isaac",
    "Defeat Isaac as Judas",
    "Complete the Boss Rush as Judas",
    "Complete the Boss Rush as Magdalene",
    "Complete the Boss Rush as Cain",
    "Defeat The Lamb as Eve",
    "Complete the Boss Rush as Eve",
    "Defeat ??? as ???",
    "Complete the Boss Rush as ???",
    "Complete the Boss Rush as Samson",
    "Defeat Isaac as Lazarus",
    "Defeat Satan as Lazarus",
    "Defeat ??? as Lazarus",
    "Defeat The Lamb as Lazarus",
    "Complete Suicide King (challenge #7)",
    "Defeat Isaac as Eden",
    "Defeat Satan as Eden",
    "Defeat ??? as Eden",
    "Defeat The Lamb as Eden",
    "Complete the Boss Rush as Eden",
    "Defeat Isaac as Azazel",
    "Defeat Satan as Azazel",
    "Defeat ??? as Azazel",
    "Defeat Isaac as The Lost",
    "Defeat Satan as The Lost",
    "Defeat ??? as The Lost",
    "Defeat The Lamb as The Lost",
    "Complete the Boss Rush as The Lost",
    "Donate 10 Coins to the Donation Machine",
    "Donate 50 Coins to the Donation Machine",
    "Donate 150 Coins to the Donation Machine",
    "Donate 400 Coins to the Donation Machine",
    "Donate 999 Coins to the Donation Machine",
    "Defeat Mom's Heart 4 times",
    "Defeat Mom's Heart 6 times",
    "Defeat Mom's Heart 7 times",
    "Take 20 items from Devil Rooms",
    "Defeat Krampus",
    "Make a Super Meat Boy by picking up 4 copies of Cube of Meat in one run",
    "Destroy 100 Poops",
    "Pick up any 2 of the following items in a single run: Roid Rage, The Virus, Growth Hormones, Experimental Treatment, and Speed Ball (Any 2 items that have the 'syringe' item tag)",
    "Use the Blood Donation Machine 30 times",
    "Blow up 30 Slot Machine",
    "Defeat The Lamb as Isaac",
    "Defeat Mom's Heart 2 times",
    "Donate 20 Coins to the Donation Machine",
    "Donate 100 Coins to the Donation Machine",
    "Donate 200 Coins to the Donation Machine",
    "Donate 600 Coins to the Donation Machine",
    "Complete Chapter 6",
    "Earn all 12 Hard mode Completion Marks as The Lost",
    "Defeat Mom's Heart 11 times and defeat??? as Eve",
    "Have 7 or more Red Heart Containers at one time",
    "Defeat Mom's Heart 3 times",
    "Defeat Mom's Heart 11 times and unlock Lazarus",
    "Become Guppy",
    "Defeat Mom's Heart 9 times",
    "Have 7 or more Red Heart Containers at one time",
    "Beat The Family Man (challenge #19), defeat Lokii, and unlock Judas",
    "Pick up both Key Pieces from the Angels in one run",
    "Defeat Mom",
    "Defeat Mom's Heart on Hard mode as Isaac",
    "Defeat Mom's Heart on Hard mode as Magdalene",
    "Defeat Mom's Heart on Hard mode as Eve",
    "Defeat Mom's Heart on Hard mode as Judas",
    "Defeat Mom's Heart on Hard mode as Cain",
    "Defeat Mom's Heart on Hard mode as Lazarus",
    "Defeat Mom's Heart on Hard mode as Azazel",
    "Defeat Mom's Heart on Hard mode as ???",
    "Defeat Mom's Heart on Hard mode as The Lost",
    "Defeat Mom's Heart on Hard mode as Eden",
    "Defeat Mom's Heart on Hard mode as Samson",
    "Become Beelzebub",
    "Defeat Hush as Isaac",
    "Defeat Hush as Magdalene",
    "Defeat Hush as Cain",
    "Defeat Hush as Judas",
    "Defeat Hush as ???",
    "Defeat Hush as Eve",
    "Defeat Hush as Samson",
    "Defeat Hush as Azazel",
    "Defeat Hush as Lazarus",
    "Defeat Hush as Eden",
    "Defeat Hush as The Lost",
    "Defeat Hush as Lilith",
    "Defeat Hush as Keeper",
    "Defeat Ultra Greed as Isaac",
    "Defeat Ultra Greed as Magdalene",
    "Defeat Ultra Greed as Cain",
    "Defeat Ultra Greed as Judas",
    "Defeat Ultra Greed as ???",
    "Defeat Ultra Greed as Eve",
    "Defeat Ultra Greed as Samson",
    "Defeat Ultra Greed as Azazel",
    "Defeat Ultra Greed as Lazarus",
    "Defeat Ultra Greed as Eden",
    "Defeat Ultra Greed as The Lost",
    "Defeat Ultra Greed as Lilith",
    "Defeat Ultra Greed as Keeper",
    "Defeat Mega Satan as Isaac",
    "Defeat Mega Satan as Magdalene",
    "Defeat Mega Satan as Cain",
    "Defeat Mega Satan as Judas",
    "Defeat Mega Satan as ???",
    "Defeat Mega Satan as Eve",
    "Defeat Mega Satan as Samson",
    "Defeat Mega Satan as Azazel",
    "Defeat Mega Satan as Lazarus",
    "Defeat Mega Satan as Eden",
    "Defeat Mega Satan as The Lost",
    "Defeat Mega Satan as Lilith",
    "Defeat Mega Satan as Keeper",
    "Defeat Isaac as Lilith",
    "Defeat ??? as Lilith",
    "Defeat Satan as Lilith",
    "Defeat The Lamb as Lilith",
    "Complete the Boss Rush as Lilith",
    "Defeat Mom's Heart on Hard mode as Lilith",
    "Complete XXXXXXXXL (challenge #21)",
    "Complete SPEED! (challenge #22)",
    "Complete Blue Bomber (challenge #23)",
    "Complete PAY TO PLAY (challenge #24)",
    "Complete Have a Heart (challenge #25)",
    "Complete I RULE! (challenge #26)",
    "Complete BRAINS! (challenge #27)",
    "Complete PRIDE DAY! (challenge #28)",
    "Complete Onan's Streak (Challenge #29)",
    "Complete The Guardian (Challenge #30)",
    "Defeat Mom's Heart 10 times",
    "Collect all items, unlock all secrets and endings up to Afterbirth",
    "Defeat Isaac as Keeper",
    "Defeat Satan as Keeper",
    "Defeat ??? as Keeper",
    "Defeat The Lamb as Keeper",
    "Complete the Boss Rush as Keeper",
    "Defeat Mom's Heart on Hard mode as Keeper",
    "Donate 2 Coins to the Greed Donation Machine",
    "Donate 14 Coins to the Greed Donation Machine",
    "Donate 33 Coins to the Greed Donation Machine",
    "Donate 68 Coins to the Greed Donation Machine",
    "Donate 111 Coins to the Greed Donation Machine",
    "Donate 234 Coins to the Greed Donation Machine",
    "Donate 439 Coins to the Greed Donation Machine",
    "Donate 666 Coins to the Greed Donation Machine",
    "Donate 879 Coins to the Greed Donation Machine",
    "Donate 1000 Coins to the Greed Donation Machine",
    "Earn all Hard mode Completion Marks as ???",
    "Earn all Hard mode Completion Marks as Isaac",
    "Earn all Hard mode Completion Marks as Magdalene",
    "Earn all Hard mode Completion Marks as Eve",
    "Earn all Hard mode Completion Marks as Eden",
    "Earn all Hard mode Completion Marks as Lazarus",
    "Use Blank Card while holding XIX - The Sun",
    "Earn all Hard mode Completion Marks as Azazel",
    "Earn all Hard mode Completion Marks as Lilith",
    "Earn all Hard mode Completion Marks as Cain",
    "Earn all Hard mode Completion Marks as Samson",
    "Earn all Hard mode Completion Marks as Judas",
    "Earn all Hard mode Completion Marks as Keeper",
    "Defeat Mom",
    "Defeat Mom",
    "Destroy 10 Tinted Rocks and defeat Mom's Heart 11 times",
    "Defeat Isaac as Cain and destroy 10 Tinted Rocks",
    "Defeat Mom",
    "Defeat Mega Satan and unlock The Negative",
    "Defeat Isaac 5 times",
    "Defeat Mom",
    "Unlock Judas and defeat It Lives!",
    "Defeat Mom",
    "Donate 999 Coins to the Greed Donation Machine",
    "Defeat Mega Satan with all 17 standard characters",
    "Defeat Mega Satan and unlock The Negative",
    "Defeat Mom",
    "Defeat Mom's Heart 11 times",
    "Defeat Mega Satan and unlock The Negative",
    "Defeat Isaac 5 times",
    "Defeat Delirium as Isaac",
    "Defeat Delirium as Magdalene",
    "Defeat Delirium as Cain",
    "Defeat Delirium as Judas",
    "Defeat Delirium as ???",
    "Defeat Delirium as Samson",
    "Defeat Delirium as Eve",
    "Defeat Delirium as Eden",
    "Defeat Delirium as Azazel",
    "Defeat Delirium as Lazarus",
    "Defeat Delirium as Lilith",
    "Defeat Delirium as The Lost",
    "Defeat Delirium as Keeper",
    "Defeat Delirium as Apollyon",
    "Defeat Ultra Greedier as Isaac",
    "Defeat Ultra Greedier as Magdalene",
    "Defeat Ultra Greedier as Cain",
    "Defeat Ultra Greedier as Judas",
    "Defeat Ultra Greedier as ???",
    "Defeat Ultra Greedier as Samson",
    "Defeat Ultra Greedier as Eve",
    "Defeat Ultra Greedier as Eden",
    "Defeat Ultra Greedier as Azazel",
    "Defeat Ultra Greedier as Lazarus",
    "Defeat Ultra Greedier as Lilith",
    "Defeat Ultra Greedier as The Lost",
    "Defeat Ultra Greedier as Keeper",
    "Defeat Ultra Greedier as Apollyon",
    "Defeat Isaac as Apollyon",
    "Defeat Satan as Apollyon",
    "Defeat ??? as Apollyon",
    "Defeat The Lamb as Apollyon",
    "Complete the Boss Rush as Apollyon",
    "Defeat Hush as Apollyon",
    "Defeat Ultra Greed as Apollyon",
    "Defeat Mega Satan as Apollyon",
    "Defeat Mom's Heart or It Lives! on Hard mode as Apollyon",
    "Earn all Hard mode Completion Marks as Apollyon",
    "Defeat Hush",
    "Complete a Victory Lap by defeating The Lamb",
    "Get a 3-win streak",
    "Get a 3-win streak (or 5 in older versions), using a different character each time",
    "Collect every entry in the Bestiary (bugged v190 - Mobs that don't exist in the bestiary are being counted. This allows Sin Collector to be unlocked without a complete bestiary)",
    "Participate in 31 Daily Challenges (they don't have to be consecutive; it will still count if Isaac dies in the first room)",
    "Defeat The Lamb in under 20 minutes",
    "Defeat The Lamb without taking Hearts, Coins, or Bombs through the entire run. Letting certain familiars (e.g. Bum Friend, Dark Bum, Bumbo or Lil Portal) or bosses (e.g. Bumbino) pick up the consumables fails this condition as well. [ 1 ]",
    "Reset 7 runs in a row using the quick-reset key",
    "Complete a Chapter (floors I and II) after Basement, start-to-finish, with only half a Heart total (can use The Lost)",
    "Obtain 50 items in a run (duplicate passive items/familiars count towards the total, e.g., multiple Breakfast)",
    "Complete Backasswards (challenge #31)",
    "Complete Aprils Fool (challenge #32)",
    "Complete Pokey Mans (challenge #33)",
    "Complete Ultra Hard (challenge #34)",
    "Complete Pong (challenge #35)",
    "Get a 5-win streak in the Daily Challenges (they don't have to be consecutive days, only the runs you play are counted)",
    "Complete 3 Victory Laps by defeating The Lamb",
    "Defeat Delirium",
    "Collect every item in the game, unlock all secrets and endings, and complete the Bestiary",
    "Defeat Mega Satan",
    "Donate 500 Coins to the Greed Donation Machine",
    "Defeat Mom's Heart 11 times",
    "Defeat It Lives! 16 times",
    "Defeat It Lives! 21 times",
    "Defeat It Lives! 30 times",
    "Defeat ??? as 3 different Characters",
    "Defeat ??? as 6 different Characters",
    "Defeat The Lamb",
    "Defeat 20 Portals",
    "Destroy 500 rocks",
    "Beat Chapter 1 without taking damage",
    "Become Beelzebub",
    "Destroy 5 rainbow poops",
    "Complete 7 Daily Challenges (by touching the trophy at the end)",
    "Pick up 5 familiars in a single run",
    "Defeat Little Horn 20 times",
    "Defeat Delirium for the 1st time",
    "Recharge using Lil' Batteries 20 times",
    "Sleep in a bed",
    "Complete 2 Victory Laps by defeating The Lamb",
    "Increase in size 5 times in a single run via Magic Mushroom, \" One makes you larger \" pills, XI - Strength, etc.",
    "Use Cards and Runes 20 times",
    "Add both the Broken Watch and the Stop Watch to your collection",
    "Purchase anything from Shops, Devil Rooms, and/or Black Markets 50 times",
    "Beat Chapter 2 without taking damage",
    "Use Pandora's Box in Dark Room",
    "Pick up any 2 of the following items/trinkets in a single run: 9 Volt, The Battery, Car Battery, AAA Battery, and Watch Battery (Any 2 items that have the 'battery' item tag)",
    "Beat Chapter 3 without taking damage",
    "Pick up any 2 technology items in a single run (Any 2 items that have the 'tech' item tag)",
    "Acquire both Key Piece 1 and Key Piece 2",
    "Open 20 Locked Chests",
    "Defeat all 5 Harbingers",
    "Defeat an Angel 10 times",
    "Beat Chapter 4 without taking damage",
    "Blow up doors and Secret Room walls 50 times",
    "Take 25 Deals with the Devil",
    "Acquire Blood Clot 10 times",
    "Collect 10 \"Tears Up\" items or pills in one run",
    "Enter 6 Shops in one run",
    "Take 25 Angel Rooms items",
    "Have The Battery, 9 Volt, and Car Battery in Isaac's collection",
    "Acquire Rubber Cement 5 times",
    "Take 50 Deals with the Devil",
    "Have Isaac die to his own explosion from Ipecac, Bob's Rotten Head, or a Horf! pill",
    "Sleep in 10 beds",
    "Use 5 Gulp! pills in one run (Placebo uses count)",
    "Spawn three charmed enemies in the same room",
    "Have 20 Blue Flies at the same time",
    "Use I - The Magician or Telepathy For Dummies while already having homing tears",
    "It's complicated",
    "It's complicated",
    "Defeat Mom's Heart or It Lives! on Hard mode as The Forgotten",
    "Defeat Isaac as The Forgotten",
    "Defeat Satan as The Forgotten",
    "Defeat ??? as The Forgotten",
    "Defeat The Lamb as The Forgotten",
    "Complete the Boss Rush as The Forgotten",
    "Defeat Hush as The Forgotten",
    "Defeat Ultra Greed as The Forgotten",
    "Defeat Ultra Greedier as The Forgotten",
    "Defeat Delirium as The Forgotten",
    "Earn all Hard mode Completion Marks as The Forgotten",
    "Collect all items, unlock all secrets and complete the Bestiary up to Afterbirth †",
    "Defeat Mom's Heart / It Lives! on hard mode as Lazarus, without dying at all",
    "Defeat Mother",
    "Collect any 3 items with the 'stars' item tag in a single run",
    "Defeat Hush 3 times",
    "Blow up The Siren 's skull after defeating her",
    "Defeat Baby Plum 10 times",
    "Allow Baby Plum to escape instead of defeating her",
    "Enter Corpse for the first time",
    "Defeat all bosses in Downpour",
    "Defeat all bosses in Mines",
    "Defeat all bosses in Mausoleum",
    "Open Mom's Chest in Home",
    "Defeat Mom's Heart or It Lives! on Hard mode as Bethany",
    "Defeat Isaac as Bethany",
    "Defeat Satan as Bethany",
    "Defeat ??? as Bethany",
    "Defeat The Lamb as Bethany",
    "Complete the Boss Rush as Bethany",
    "Defeat Ultra Greed as Bethany",
    "Defeat Hush as Bethany",
    "Defeat Ultra Greedier as Bethany",
    "Defeat Delirium as Bethany",
    "Earn all Hard mode Completion Marks as Bethany",
    "Defeat Mega Satan as Bethany",
    "Defeat Mom's Heart or It Lives! on Hard mode as Jacob and Esau",
    "Defeat Isaac as Jacob and Esau",
    "Defeat Satan as Jacob and Esau",
    "Defeat ??? as Jacob and Esau",
    "Defeat The Lamb as Jacob and Esau",
    "Complete Boss Rush as Jacob and Esau",
    "Defeat Ultra Greed as Jacob and Esau",
    "Defeat Hush as Jacob and Esau",
    "Defeat Ultra Greedier as Jacob and Esau",
    "Defeat Delirium as Jacob and Esau",
    "Earn all Hard mode Completion Marks as Jacob and Esau",
    "Defeat Mega Satan as Jacob and Esau",
    "Defeat Mother as Isaac",
    "Defeat The Beast as Isaac",
    "Defeat Mother as Magdalene",
    "Defeat The Beast as Magdalene",
    "Defeat Mother as Cain",
    "Defeat The Beast as Cain",
    "Defeat Mother as Judas",
    "Defeat The Beast as Judas",
    "Defeat Mother as ???",
    "Defeat The Beast as ???",
    "Defeat Mother as Eve",
    "Defeat The Beast as Eve",
    "Defeat Mother as Samson",
    "Defeat The Beast as Samson",
    "Defeat Mother as Azazel",
    "Defeat The Beast as Azazel",
    "Defeat Mother as Lazarus",
    "Defeat The Beast as Lazarus",
    "Defeat Mother as Eden",
    "Defeat The Beast as Eden",
    "Defeat Mother as The Lost",
    "Defeat The Beast as The Lost",
    "Defeat Mother as Lilith",
    "Defeat The Beast as Lilith",
    "Defeat Mother as Keeper",
    "Defeat The Beast as Keeper",
    "Defeat Mother as Apollyon",
    "Defeat The Beast as Apollyon",
    "Defeat Mother as The Forgotten",
    "Defeat The Beast as The Forgotten",
    "Defeat Mother as Bethany",
    "Defeat The Beast as Bethany",
    "Defeat Mother as Jacob and Esau",
    "Defeat The Beast as Jacob and Esau",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Isaac",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Magdalene",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Cain",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Judas",
    "Use Red Key / Cracked Key to open the hidden closet in Home as ???",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Eve",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Samson",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Azazel",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Lazarus",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Eden",
    "Use Red Key / Cracked Key to open the hidden closet in Home as The Lost",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Lilith",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Keeper",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Apollyon",
    "Use Red Key / Cracked Key to open the hidden closet in Home as The Forgotten",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Bethany",
    "Use Red Key / Cracked Key to open the hidden closet in Home as Jacob and Esau",
    "Defeat The Beast as Tainted Isaac",
    "Defeat The Beast as Tainted Magdalene",
    "Defeat The Beast as Tainted Cain",
    "Defeat The Beast as Tainted Judas",
    "Defeat The Beast as Tainted ???",
    "Defeat The Beast as Tainted Eve",
    "Defeat The Beast as Tainted Samson",
    "Defeat The Beast as Tainted Azazel",
    "Defeat The Beast as Tainted Lazarus",
    "Defeat The Beast as Tainted Eden",
    "Defeat The Beast as Tainted Lost",
    "Defeat The Beast as Tainted Lilith",
    "Defeat The Beast as Tainted Keeper",
    "Defeat The Beast as Tainted Apollyon",
    "Defeat The Beast as Tainted Forgotten",
    "Defeat The Beast as Tainted Bethany",
    "Defeat The Beast as Tainted Jacob",
    "Unlock Bethany, Blood Bag, and It Lives!",
    "Defeat Satan as Bethany, defeat Mom's Heart 11 times, and unlock Maggy's Faith",
    "Defeat Mother",
    "Defeat Mother",
    "Defeat Mom's Heart 11 times and unlock Marbles",
    "Unlock Tainted Forgotten",
    "Unlock Tainted Cain",
    "Unlock Tainted Jacob",
    "Unlock Tainted Eden",
    "Complete Scat Man (challenge #36)",
    "Complete Bloody Mary (challenge #37)",
    "Complete Baptism by Fire (challenge #38)",
    "Complete Isaac's Awakening (challenge #39)",
    "Complete Seeing Double (challenge #40)",
    "Complete Pica Run (challenge #41)",
    "Donate to Battery Bums until they pay out with an item 5 times",
    "Defeat Ultra Greedier as Tainted Lost",
    "Defeat Ultra Greedier as Tainted Judas",
    "Defeat Ultra Greedier as Tainted Lilith",
    "Defeat Ultra Greedier as Tainted Eve",
    "Defeat Ultra Greedier as Tainted ???",
    "Defeat Ultra Greedier as Tainted Bethany",
    "Defeat Ultra Greedier as Tainted Magdalene",
    "Complete Hot Potato (challenge #42)",
    "Complete Cantripped (challenge #43)",
    "Complete Red Redemption (challenge #44)",
    "Defeat Ultra Greedier as Tainted Cain",
    "Defeat Ultra Greedier as Tainted Samson",
    "Defeat Ultra Greedier as Tainted Keeper",
    "Defeat Ultra Greedier as Tainted Forgotten",
    "Complete DELETE THIS (challenge #45)",
    "Defeat Ultra Greedier as Tainted Azazel",
    "Defeat Ultra Greedier as Tainted Apollyon",
    "Defeat Ultra Greedier as Tainted Isaac",
    "Defeat Ultra Greedier as Tainted Jacob",
    "Defeat Ultra Greedier as Tainted Lazarus",
    "Defeat Ultra Greedier as Tainted Eden",
    "Kill 10 Battery Bums",
    "After breaking Hornfel's minecart, kill him before he can escape",
    "Earn all Hard mode Completion Marks for all non-Tainted characters",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Isaac",
    "Defeat Mother as Tainted Isaac",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Magdalene",
    "Defeat Mother as Tainted Magdalene",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Cain",
    "Defeat Mother as Tainted Cain",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Judas",
    "Defeat Mother as Tainted Judas",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted ???",
    "Defeat Mother as Tainted ???",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Eve",
    "Defeat Mother as Tainted Eve",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Samson",
    "Defeat Mother as Tainted Samson",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Azazel",
    "Defeat Mother as Tainted Azazel",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Lazarus",
    "Defeat Mother as Tainted Lazarus",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Eden",
    "Defeat Mother as Tainted Eden",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Lost",
    "Defeat Mother as Tainted Lost",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Lilith",
    "Defeat Mother as Tainted Lilith",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Keeper",
    "Defeat Mother as Tainted Keeper",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Apollyon",
    "Defeat Mother as Tainted Apollyon",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Forgotten",
    "Defeat Mother as Tainted Forgotten",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Bethany",
    "Defeat Mother as Tainted Bethany",
    "Defeat Isaac, ???, Satan, and The Lamb as Tainted Jacob",
    "Defeat Mother as Tainted Jacob",
    "Spend 40+ coins in a single Shop",
    "In a single run, obtain 99 Coins, then spend all of them",
    "Defeat Delirium as Tainted Isaac",
    "Defeat Delirium as Tainted Magdalene",
    "Defeat Delirium as Tainted Cain",
    "Defeat Delirium as Tainted Judas",
    "Defeat Delirium as Tainted ???",
    "Defeat Delirium as Tainted Eve",
    "Defeat Delirium as Tainted Samson",
    "Defeat Delirium as Tainted Azazel",
    "Defeat Delirium as Tainted Lazarus",
    "Defeat Delirium as Tainted Eden",
    "Defeat Delirium as Tainted Lost",
    "Defeat Delirium as Tainted Lilith",
    "Earn all 12 Hard mode Completion Marks with all 17 normal characters",
    "Defeat Delirium as Tainted Apollyon",
    "Defeat Delirium as Tainted Forgotten",
    "Defeat Delirium as Tainted Bethany",
    "Defeat Delirium as Tainted Jacob",
    "Defeat Mega Satan as Tainted Isaac",
    "Defeat Mega Satan as Tainted Magdalene",
    "Defeat Mega Satan as Tainted Cain",
    "Defeat Mega Satan as Tainted Judas",
    "Defeat Mega Satan as Tainted ???",
    "Defeat Mega Satan as Tainted Eve",
    "Defeat Mega Satan as Tainted Samson",
    "Defeat Mega Satan as Tainted Azazel",
    "Defeat Mega Satan as Tainted Lazarus",
    "Defeat Mega Satan as Tainted Eden",
    "Defeat Mega Satan as Tainted Lost",
    "Defeat Mega Satan as Tainted Lilith",
    "Defeat Mega Satan as Tainted Keeper",
    "Defeat Mega Satan as Tainted Apollyon",
    "Defeat Mega Satan as Tainted Forgotten",
    "Defeat Mega Satan as Tainted Bethany",
    "Defeat Mega Satan as Tainted Jacob",
    "Defeat Hush and Boss Rush as Tainted Isaac",
    "Defeat Hush and Boss Rush as Tainted Magdalene",
    "Defeat Hush and Boss Rush as Tainted Cain",
    "Defeat Hush and Boss Rush as Tainted Judas",
    "Defeat Hush and Boss Rush as Tainted ???",
    "Defeat Hush and Boss Rush as Tainted Eve",
    "Defeat Hush and Boss Rush as Tainted Samson",
    "Defeat Hush and Boss Rush as Tainted Azazel",
    "Defeat Hush and Boss Rush as Tainted Lazarus",
    "Defeat Hush and Boss Rush as Tainted Eden",
    "Defeat Hush and Boss Rush as Tainted Lost",
    "Defeat Hush and Boss Rush as Tainted Lilith",
    "Defeat Hush and Boss Rush as Tainted Keeper",
    "Defeat Hush and Boss Rush as Tainted Apollyon",
    "Defeat Hush and Boss Rush as Tainted Forgotten",
    "Defeat Hush and Boss Rush as Tainted Bethany",
    "Defeat Hush and Boss Rush as Tainted Jacob",
    "Defeat Mother",
    "Earn all 12 Hard mode Completion Marks for all 34 characters",
    "Unlock all the other achievements and collect every item in the game",
    "Play an online co-op run",
    "Win an online co-op run",
    "Win an Online Daily Challenge run",
    "Unlock all other 640 achievements and collect every single item in the game",
]);

export function getAchievementName(id: number): string {
    return AchievementNames[id] ?? `Achievement #${id}`;
}

export function getAchievementUnlock(id: number): string {
    return AchievementUnlocks[id] ?? '';
}

export function getAchievementSprite(id: number, name?: string): string {
    const padId = id.toString().padStart(3, '0');
    const achName = name ?? AchievementNames[id] ?? '';
    const sanitizedName = achName
        .replace(/[\s/:]/g, '_')
        .replace(/\?/g, '_');
    return `${padId}_${sanitizedName}.png`;
}
