/**
 * Listado oficial de los 732 Coleccionables (Collection Page) del juego.
 */

export const ItemNames = Object.freeze([
    "", // Índice 0 no usado (1-indexed)
    "The Sad Onion",
    "The Inner Eye",
    "Spoon Bender",
    "Cricket's Head",
    "My Reflection",
    "Number One",
    "Blood of the Martyr",
    "Brother Bobby",
    "Skatole",
    "Halo of Flies",
    "1UP",
    "Magic Mushroom",
    "The Virus",
    "Roid Rage",
    " 3",
    "Raw Liver",
    "Skeleton Key",
    "A Dollar",
    "Boom!",
    "Transcendence",
    "The Compass",
    "Lunch",
    "Dinner",
    "Dessert",
    "Breakfast",
    "Rotten Meat",
    "Wooden Spoon",
    "The Belt",
    "Mom's Underwear",
    "Mom's Heels",
    "Mom's Lipstick",
    "Wire Coat Hanger",
    "The Bible",
    "The Book of Belial",
    "The Necronomicon",
    "The Poop",
    "Mr. Boom",
    "Tammy's Head",
    "Mom's Bra",
    "Kamikaze",
    "Mom's Pad",
    "Bob's Rotten Head",
    "Item 43",
    "Teleport!",
    "Yum Heart",
    "Lucky Foot",
    "Doctor's Remote",
    "Cupid's Arrow",
    "Shoop Da Whoop",
    "Steven",
    "Pentagram",
    "Dr. Fetus",
    "Magneto",
    "Treasure Map",
    "Mom's Eye",
    "Lemon Mishap",
    "Distant Admiration",
    "Book of Shadows",
    "Item 59",
    "The Ladder",
    "Item 61",
    "Charm of the Vampire",
    "The Battery",
    "Steam Sale",
    "Anarchist Cookbook",
    "The Hourglass",
    "Sister Maggy",
    "Technology",
    "Chocolate Milk",
    "Growth Hormones",
    "Mini Mush",
    "Rosary",
    "Cube of Meat",
    "A Quarter",
    "PhD",
    "X-Ray Vision",
    "My Little Unicorn",
    "Book of Revelations",
    "The Mark",
    "The Pact",
    "Dead Cat",
    "Lord of the Pit",
    "The Nail",
    "We Need To Go Deeper!",
    "Deck of Cards",
    "Monstro's Tooth",
    "Loki's Horns",
    "Little Chubby",
    "Spider Bite",
    "The Small Rock",
    "Spelunker Hat",
    "Super Bandage",
    "The Gamekid",
    "Sack of Pennies",
    "Robo-Baby",
    "Little C.H.A.D.",
    "The Book of Sin",
    "The Relic",
    "Little Gish",
    "Little Steven",
    "The Halo",
    "Mom's Bottle of Pills",
    "The Common Cold",
    "The Parasite",
    "The D6",
    "Mr. Mega",
    "Pinking Shears",
    "The Wafer",
    "Money = Power",
    "Mom's Contacts",
    "The Bean",
    "Guardian Angel",
    "Demon Baby",
    "Mom's Knife",
    "Ouija Board",
    "9 Volt",
    "Dead Bird",
    "Brimstone",
    "Blood Bag",
    "Odd Mushroom (Thin)",
    "Odd Mushroom (Thick)",
    "Whore of Babylon",
    "Monster Manual",
    "Dead Sea Scrolls",
    "Bobby-Bomb",
    "Razor Blade",
    "Forget Me Now",
    "Forever Alone",
    "Bucket of Lard",
    "A Pony",
    "Bomb Bag",
    "A Lump of Coal",
    "Guppy's Paw",
    "Guppy's Tail",
    "IV Bag",
    "Best Friend",
    "Remote Detonator",
    "Stigmata",
    "Mom's Purse",
    "Bob's Curse",
    "Pageant Boy",
    "Scapular",
    "Speed Ball",
    "Bum Friend",
    "Guppy's Head",
    "Prayer Card",
    "Notched Axe",
    "Infestation",
    "Ipecac",
    "Tough Love",
    "The Mulligan",
    "Technology 2",
    "Mutant Spider",
    "Chemical Peel",
    "The Peeper",
    "Habit",
    "Bloody Lust",
    "Crystal Ball",
    "Spirit of the Night",
    "Crack The Sky",
    "Ankh",
    "Celtic Cross",
    "Ghost Baby",
    "The Candle",
    "Cat-o-nine-tails",
    "D20",
    "Harlequin Baby",
    "Epic Fetus",
    "Polyphemus",
    "Daddy Longlegs",
    "Spider Butt",
    "Sacrificial Dagger",
    "Mitre",
    "Rainbow Baby",
    "Dad's Key",
    "Stem Cells",
    "Portable Slot",
    "Holy Water",
    "Fate",
    "The Black Bean",
    "White Pony",
    "Sacred Heart",
    "Toothpicks",
    "Holy Grail",
    "Dead Dove",
    "Blood Rights",
    "Guppy's Hairball",
    "Abel",
    "SMB Super Fan",
    "Pyro",
    "3 Dollar Bill",
    "Telepathy for Dummies",
    "Meat!",
    "Magic 8 Ball",
    "Mom's Coin Purse",
    "Squeezy",
    "Jesus Juice",
    "Box",
    "Mom's Key",
    "Mom's Eyeshadow",
    "Iron Bar",
    "Midas Touch",
    "Humbling Bundle",
    "Fanny Pack",
    "Sharp Plug",
    "Guillotine",
    "Ball of Bandages",
    "Champion Belt",
    "Butt Bombs",
    "Gnawed Leaf",
    "Spiderbaby",
    "Guppy's Collar",
    "Lost Contact",
    "Anemic",
    "Goat Head",
    "Ceremonial Robes",
    "Mom's Wig",
    "Placenta",
    "Old Bandage",
    "Sad Bombs",
    "Rubber Cement",
    "Anti-Gravity",
    "Pyromaniac",
    "Cricket's Body",
    "Gimpy",
    "Black Lotus",
    "Piggy Bank",
    "Mom's Perfume",
    "Monstro's Lung",
    "Abaddon",
    "Ball of Tar",
    "Stop Watch",
    "Tiny Planet",
    "Infestation 2",
    "Item 235",
    "E. Coli",
    "Death's Touch",
    "Key Piece #1",
    "Key Piece #2",
    "Experimental Treatment",
    "Contract From Below",
    "Infamy",
    "Trinity Shield",
    "Tech.5",
    "20 20",
    "Blue Map",
    "BFFS!",
    "Hive Mind",
    "There's Options",
    "Bogo Bombs",
    "Starter Deck",
    "Little Baggy",
    "Magic Scab",
    "Blood Clot",
    "Screw",
    "Hot Bombs",
    "Fire Mind",
    "Missing No.",
    "Dark Matter",
    "Black Candle",
    "Proptosis",
    "Missing Page 2",
    "Clear Rune",
    "Smart Fly",
    "Dry Baby",
    "Juicy Sack",
    "Robo-Baby 2.0",
    "Rotten Baby",
    "Headless Baby",
    "Leech",
    "Mystery Sack",
    "BBF",
    "Bob's Brain",
    "Best Bud",
    "Lil' Brimstone",
    "Isaac's Heart",
    "Lil' Haunt",
    "Dark Bum",
    "Big Fan",
    "Sissy Long Legs",
    "Punching Bag",
    "How To Jump",
    "D100",
    "D4",
    "D10",
    "Blank Card",
    "Book of Secrets",
    "Box of Spiders",
    "Red Candle",
    "The Jar",
    "Flush!",
    "The Satanic Bible",
    "Head of Krampus",
    "Butter Bean",
    "Magic Fingers",
    "Converter",
    "Pandora's Box",
    "Unicorn Stump",
    "Taurus",
    "Aries",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
    "Eve's Mascara",
    "Judas' Shadow",
    "Maggy's Bow",
    "Holy Mantle",
    "Thunder Thighs",
    "Strange Attractor",
    "Cursed Eye",
    "Mysterious Liquid",
    "Gemini",
    "Cain's Other Eye",
    "   's Only Friend",
    "Samson's Chains",
    "Mongo Baby",
    "Isaac's Tears",
    "Undefined",
    "Scissors",
    "Breath of Life",
    "The Polaroid",
    "The Negative",
    "The Ludovico Technique",
    "Soy Milk",
    "Godhead",
    "Lazarus' Rags",
    "The Mind",
    "The Body",
    "The Soul",
    "Dead Onion",
    "Broken Watch",
    "Boomerang",
    "Safety Pin",
    "Caffeine Pill",
    "Torn Photo",
    "Blue Cap",
    "Latch Key",
    "Match Book",
    "Synthoil",
    "A Snack",
    "Diplopia",
    "Placebo",
    "Wooden Nickel",
    "Toxic Shock",
    "Mega Bean",
    "Glass Cannon",
    "Bomber Boy",
    "Crack Jacks",
    "Mom's Pearls",
    "Car Battery",
    "Box of Friends",
    "The Wiz",
    "8 Inch Nails",
    "Incubus",
    "Fate's Reward",
    "Lil Chest",
    "Sworn Protector",
    "Friend Zone",
    "Lost Fly",
    "Scatter Bombs",
    "Sticky Bombs",
    "Epiphora",
    "Continuum",
    "Mr. Dolly",
    "Curse of the Tower",
    "Charged Baby",
    "Dead Eye",
    "Holy Light",
    "Host Hat",
    "Restock",
    "Bursting Sack",
    "Number two",
    "Pupula Duplex",
    "Pay To Play",
    "Eden's Blessing",
    "Friendly Ball",
    "Tear Detonator",
    "Lil Gurdy",
    "Bumbo",
    "D12",
    "Censer",
    "Key Bum",
    "Rune Bag",
    "Seraphim",
    "Betrayal",
    "Zodiac",
    "Serpent's Kiss",
    "Marked",
    "Tech X",
    "Ventricle Razor",
    "Tractor Beam",
    "God's Flesh",
    "Maw of the Void",
    "Spear of Destiny",
    "Explosivo",
    "Chaos",
    "Spider Mod",
    "Farting Baby",
    "GB Bug",
    "D8",
    "Purity",
    "Athame",
    "Empty Vessel",
    "Evil Eye",
    "Lusty Blood",
    "Cambion Conception",
    "Immaculate Conception",
    "More Options",
    "Crown of Light",
    "Deep Pockets",
    "Succubus",
    "Fruit Cake",
    "Teleport 2.0",
    "Black Powder",
    "Kidney Bean",
    "Glowing Hour Glass",
    "Circle of Protection",
    "Sack Head",
    "Night Light",
    "Obsessed Fan",
    "Mine Crafter",
    "PJs",
    "Head of the Keeper",
    "Papa Fly",
    "Multidimensional Baby",
    "Glitter Bombs",
    "My Shadow",
    "Jar of Flies",
    "Lil Loki",
    "Milk!",
    "D7",
    "Binky",
    "Mom's Box",
    "Kidney Stone",
    "Mega Blast",
    "Dark Prince's Crown",
    "Apple!",
    "Lead Pencil",
    "Dog Tooth",
    "Dead Tooth",
    "Linger Bean",
    "Shard of Glass",
    "Metal Plate",
    "Eye of Greed",
    "Tarot Cloth",
    "Varicose Veins",
    "Compound Fracture",
    "Polydactyly",
    "Dad's Lost Coin",
    "Midnight Snack",
    "Cone Head",
    "Belly Button",
    "Sinus Infection",
    "Glaucoma",
    "Parasitoid",
    "Eye of Belial",
    "Sulfuric Acid",
    "Glyph of Balance",
    "Analog Stick",
    "Contagion",
    "Finger!",
    "Shade",
    "Depression",
    "Hushy",
    "Lil Monstro",
    "King Baby",
    "Big Chubby",
    "Broken Glass Cannon",
    "Plan C",
    "D1",
    "Void",
    "Pause",
    "Smelter",
    "Compost",
    "Dataminer",
    "Clicker",
    "Mama Mega!",
    "Wait What ",
    "Crooked Penny",
    "Dull Razor",
    "Potato Peeler",
    "Metronome",
    "D infinity",
    "Eden's Soul",
    "Acid Baby",
    "YO LISTEN!",
    "Adrenaline",
    "Jacob's Ladder",
    "Ghost Pepper",
    "Euthanasia",
    "Camo Undies",
    "Duality",
    "Eucharist",
    "Sack of Sacks",
    "Greed's Gullet",
    "Large Zit",
    "Little Horn",
    "Brown Nugget",
    "Poke Go",
    "BackStabber",
    "Sharp Straw",
    "Mom's Razor",
    "Bloodshot Eye",
    "Delirious",
    "Angry Fly",
    "Black Hole",
    "Bozo",
    "Broken Modem",
    "Mystery Gift",
    "Sprinkler",
    "Fast Bombs",
    "Buddy in a Box",
    "Lil Delirium",
    "Jumper Cables",
    "Coupon",
    "Telekinesis",
    "Moving Box",
    "Technology Zero",
    "Leprosy",
    "7 Seals",
    "Mr. Me!",
    "Angelic Prism",
    "Pop!",
    "Death's List",
    "Haemolacria",
    "Lachryphagy",
    "Trisagion",
    "Schoolbag",
    "Blanket",
    "Sacrificial Altar",
    "Lil Spewer",
    "Marbles",
    "Mystery Egg",
    "Flat Stone",
    "Marrow",
    "Slipped Rib",
    "Hallowed Ground",
    "Pointy Rib",
    "Book of the Dead",
    "Dad's Ring",
    "Divorce Papers",
    "Jaw Bone",
    "Brittle Bones",
    "Broken Shovel",
    "Broken Shovel",
    "Mom's Shovel",
    "Mucormycosis",
    "2Spooky",
    "Golden Razor",
    "Sulfur",
    "Fortune Cookie",
    "Eye Sore",
    "120 Volt",
    "It Hurts",
    "Almond Milk",
    "Rock Bottom",
    "Nancy Bombs",
    "A Bar of Soap",
    "Blood Puppy",
    "Dream Catcher",
    "Paschal Candle",
    "Divine Intervention",
    "Blood Oath",
    "Playdough Cookie",
    "Orphan Socks",
    "Eye of the Occult",
    "Immaculate Heart",
    "Monstrance",
    "The Intruder",
    "Dirty Mind",
    "Damocles",
    "Free Lemonade",
    "Spirit Sword",
    "Red Key",
    "Psy Fly",
    "Wavy Cap",
    "Rocket in a Jar",
    "Book of Virtues",
    "Alabaster Box",
    "The Stairway",
    "Item 587",
    "Sol",
    "Luna",
    "Mercurius",
    "Venus",
    "Terra",
    "Mars",
    "Jupiter",
    "Saturnus",
    "Uranus",
    "Neptunus",
    "Pluto",
    "Voodoo Head",
    "Eye Drops",
    "Act of Contrition",
    "Member Card",
    "Battery Pack",
    "Mom's Bracelet",
    "The Scooper",
    "Ocular Rift",
    "Boiled Baby",
    "Freezer Baby",
    "Eternal D6",
    "Bird Cage",
    "Larynx",
    "Lost Soul",
    "Item 613",
    "Blood Bombs",
    "Lil' Dumpy",
    "Bird's Eye",
    "Lodestone",
    "Rotten Tomato",
    "Birthright",
    "Item 620",
    "Red Stew",
    "Genesis",
    "Sharp Key",
    "Booster Pack",
    "Mega Mush",
    "Knife Piece 1",
    "Knife Piece 2",
    "Death Certificate",
    "Bot Fly",
    "Item 630",
    "Meat Cleaver",
    "Evil Charm",
    "Dogma",
    "Purgatory",
    "Stitches",
    "R Key",
    "Knockout Drops",
    "Eraser",
    "Yuck Heart",
    "Urn of Souls",
    "Akeldama",
    "Magic Skin",
    "Revelation",
    "Consolation Prize",
    "Tinytoma",
    "Brimstone bombs",
    "4.5 Volt",
    "Pill Crusher",
    "Fruity Plum",
    "Plum Flute",
    "Star of Bethlehem",
    "Cube Baby",
    "Vade Retro",
    "False PHD",
    "Spin to Win",
    "Item 656",
    "Vasculitis",
    "Giant Cell",
    "Tropicamide",
    "Card Reading",
    "Quints",
    "Item 662",
    "Tooth and Nail",
    "Binge Eater",
    "Guppy's Eye",
    "Item 666",
    "Strawman",
    "Dad's Note",
    "Sausage",
    "Options ",
    "Candy Heart",
    "A Pound of Flesh",
    "Redemption",
    "Spirit Shackles",
    "Cracked Orb",
    "Empty Heart",
    "Astral Projection",
    "C Section",
    "Lil Abaddon",
    "Montezuma's Revenge",
    "Lil Portal",
    "Worm Friend",
    "Bone Spurs",
    "Hungry Soul",
    "Jar of Wisps",
    "Soul Locket",
    "Friend Finder",
    "Inner Child",
    "Glitched Crown",
    "Belly Jelly",
    "Sacred Orb",
    "Sanguine Bond",
    "The Swarm",
    "Heartbreak",
    "Bloody Gust",
    "Salvation",
    "Vanishing Twin",
    "Twisted Pair",
    "Azazel's Rage",
    "Echo Chamber",
    "Isaac's Tomb",
    "Vengeful Spirit",
    "Esau Jr.",
    "Berserk!",
    "Dark Arts",
    "Abyss",
    "Supper",
    "Stapler",
    "Suplex!",
    "Bag of Crafting",
    "Flip",
    "Lemegeton",
    "Sumptorium",
    "Recall",
    "Hold",
    "Keeper's Sack",
    "Keeper's Kin",
    "Item 718",
    "Keeper's Box",
    "Everything Jar",
    "TMTRAINER",
    "Anima Sola",
    "Spindown Dice",
    "Hypercoagulation",
    "IBS",
    "Hemoptysis",
    "Ghost Bombs",
    "Gello",
    "Decap Attack",
    "Glass Eye",
    "Stye",
    "Mom's Ring",
]);

/**
 * Obtiene el nombre del coleccionable por su ID (1..732).
 * @param {number} id
 * @returns {string}
 */
export function getItemName(id) {
    return ItemNames[id] ?? `Item_${id}`;
}

/**
 * Obtiene el ID del coleccionable por su nombre exacto.
 * @param {string} name
 * @returns {number}
 */
export function getItemId(name) {
    const idx = ItemNames.findIndex(n => n.toLowerCase() === name.toLowerCase());
    return idx > 0 ? idx : -1;
}
